{
	"schema_version": "1.6.0",
	"id": "MAL-2025-953",
	"modified": "2025-02-03T17:07:38Z",
	"published": "2025-02-03T17:07:38Z",
	"summary": "Malicious code in private-test-1 (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "private-test-1",
				"purl": "pkg:pypi/private-test-1"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/private-test-1/MAL-2025-953.json"
			}
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2025-00494",
				"import_time": "2025-02-03T18:38:07.737654648Z",
				"modified_time": "2025-02-03T17:07:38Z",
				"sha256": "f9ada75e893f2910458e09e6d6fa4f7a4b293c6ba29daf79d425f82f55e6bfa2",
				"source": "reversing-labs",
				"versions": [
					"1.0.0"
				]
			}
		]
	}
}
