{
	"schema_version": "1.6.0",
	"id": "PYSEC-2023-290",
	"modified": "2024-11-21T14:22:59.461917Z",
	"published": "2023-01-20T19:15:00Z",
	"details": "An issue was discovered with assimp 5.1.4, a use after free occurred in function ColladaParser::ExtractDataObjectFromChannel in file /code/AssetLib/Collada/ColladaParser.cpp.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pyassimp",
				"purl": "pkg:pypi/pyassimp"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"0.1",
				"3.3",
				"4.1.1",
				"4.1.2",
				"4.1.3",
				"4.1.4",
				"5.2.5"
			],
			"database_specific": {
				"source": "https://github.com/pypa/advisory-database/blob/main/vulns/pyassimp/PYSEC-2023-290.yaml"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://github.com/assimp/assimp/issues/4286"
		}
	]
}
