{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5105",
	"modified": "2024-06-25T13:35:07Z",
	"published": "2024-06-25T13:35:07Z",
	"summary": "Malicious code in eeeeeeeeeeeee344324f (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "eeeeeeeeeeeee344324f",
				"purl": "pkg:pypi/eeeeeeeeeeeee344324f"
			},
			"versions": [
				"1.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/eeeeeeeeeeeee344324f/MAL-2024-5105.json"
			}
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-03885",
				"import_time": "2024-06-28T02:48:54.506154956Z",
				"modified_time": "2024-06-25T13:35:07Z",
				"sha256": "ec8bb4faf2cc6e1841c4d75361e1bd4ce999f4f12c7336cb2a063c92535f264f",
				"source": "reversing-labs",
				"versions": [
					"1.0"
				]
			}
		]
	}
}
