{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5962",
	"modified": "2024-10-24T01:01:59Z",
	"published": "2024-06-25T13:42:11Z",
	"summary": "Malicious code in sadonion (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "sadonion",
				"purl": "pkg:pypi/sadonion"
			},
			"versions": [
				"1.0",
				"1.1"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/sadonion/MAL-2024-5962.json"
			}
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04763",
				"import_time": "2024-06-28T02:50:39.239425212Z",
				"modified_time": "2024-06-25T13:42:11Z",
				"sha256": "97b5e30d091f093ad72c2776ac351b964693ed73176221c380a69c40ebc2f5b0",
				"source": "reversing-labs",
				"versions": [
					"1.0",
					"1.1"
				]
			},
			{
				"id": "RLUA-2024-09227",
				"import_time": "2024-10-24T01:00:08.510836794Z",
				"modified_time": "2024-10-16T14:50:56Z",
				"sha256": "757b4e4b279ae7654e00a6e0a58ec5f395a1df2613c3f6893e2744d70a8f9c48",
				"source": "reversing-labs"
			}
		]
	}
}
