{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5659",
	"modified": "2024-10-24T01:01:59Z",
	"published": "2024-06-25T13:39:36Z",
	"aliases": [
		"SNYK-PYTHON-PYCOLORINGPKGSV2-5932108"
	],
	"summary": "Malicious code in pycoloringpkgsv2 (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pycoloringpkgsv2",
				"purl": "pkg:pypi/pycoloringpkgsv2"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pycoloringpkgsv2/MAL-2024-5659.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCOLORINGPKGSV2-5932108"
		},
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04442",
				"import_time": "2024-06-28T02:50:00.663626318Z",
				"modified_time": "2024-06-25T13:39:36Z",
				"sha256": "d2f9935c431feb27f39f5cfc4da5955d709c2f2a1812fddfd5f2c0623202c93d",
				"source": "reversing-labs",
				"versions": [
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-08878",
				"import_time": "2024-10-24T00:59:47.943666885Z",
				"modified_time": "2024-10-16T14:47:24Z",
				"sha256": "80778f2b65a6191f219e8e72036fdab97a66f1b0fb96619c481cbbaff8343024",
				"source": "reversing-labs"
			}
		]
	}
}
