{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5690",
	"modified": "2024-10-24T01:01:59Z",
	"published": "2024-06-25T13:39:52Z",
	"aliases": [
		"SNYK-PYTHON-PYCRYPTOLIBRARY-5932174"
	],
	"summary": "Malicious code in pycryptolibrary (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pycryptolibrary",
				"purl": "pkg:pypi/pycryptolibrary"
			},
			"versions": [
				"2.0.0",
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pycryptolibrary/MAL-2024-5690.json"
			}
		}
	],
	"references": [
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCRYPTOLIBRARY-5932174"
		},
		{
			"type": "ADVISORY",
			"url": "https://research.jfrog.com/malicious-packages/"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04473",
				"import_time": "2024-06-28T02:50:04.375321246Z",
				"modified_time": "2024-06-25T13:39:52Z",
				"sha256": "aa5452050301cff7d0ed80ae01051f8b1e8aa4e9220c1e8dce27a5b6264393ec",
				"source": "reversing-labs",
				"versions": [
					"2.0.0",
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-08910",
				"import_time": "2024-10-24T00:59:50.006765782Z",
				"modified_time": "2024-10-16T14:47:45Z",
				"sha256": "b94c2c7b993fe4ebb0aeed0f85b336950690d064278bb129f3322096c734e2d5",
				"source": "reversing-labs"
			}
		]
	}
}
