{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5644",
	"modified": "2024-06-25T13:39:28Z",
	"published": "2024-06-25T13:39:28Z",
	"summary": "Malicious code in pyapicolorv2 (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pyapicolorv2",
				"purl": "pkg:pypi/pyapicolorv2"
			},
			"versions": [
				"0.0.1"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pyapicolorv2/MAL-2024-5644.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://github.com/DataDog/malicious-software-packages-dataset"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04426",
				"import_time": "2024-06-28T02:49:58.842505741Z",
				"modified_time": "2024-06-25T13:39:28Z",
				"sha256": "fd6ec109861d6c4a7725f780df1cfe9569f60ab3d12d0498a4d23e27258a731b",
				"source": "reversing-labs",
				"versions": [
					"0.0.1"
				]
			}
		]
	}
}
