{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5772",
	"modified": "2024-06-25T13:40:38Z",
	"published": "2024-06-25T13:40:38Z",
	"summary": "Malicious code in pysiyte (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pysiyte",
				"purl": "pkg:pypi/pysiyte"
			},
			"versions": [
				"1.9"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pysiyte/MAL-2024-5772.json"
			}
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04568",
				"import_time": "2024-06-28T02:50:15.57127228Z",
				"modified_time": "2024-06-25T13:40:38Z",
				"sha256": "054375cf45e4f7015f66e5f6b328dd3036a6ca9199abd45d769c5a5fdf183bea",
				"source": "reversing-labs",
				"versions": [
					"1.9"
				]
			}
		]
	}
}
