{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5654",
	"modified": "2024-06-25T13:39:34Z",
	"published": "2024-06-25T13:39:34Z",
	"summary": "Malicious code in pyclys (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pyclys",
				"purl": "pkg:pypi/pyclys"
			},
			"versions": [
				"0.2.0",
				"0.1.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pyclys/MAL-2024-5654.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://research.jfrog.com/malicious-packages/"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04437",
				"import_time": "2024-06-28T02:50:00.045383549Z",
				"modified_time": "2024-06-25T13:39:34Z",
				"sha256": "a031ac1a5a1ba20d3fd72498d76649fd780fc01c83696a45023b1c97357b62ce",
				"source": "reversing-labs",
				"versions": [
					"0.2.0",
					"0.1.0"
				]
			}
		]
	}
}
