{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5541",
	"modified": "2024-10-24T01:01:59Z",
	"published": "2024-06-25T13:38:39Z",
	"aliases": [
		"SNYK-PYTHON-PIPSQLIPKGV1-5932205"
	],
	"summary": "Malicious code in pipsqlipkgv1 (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pipsqlipkgv1",
				"purl": "pkg:pypi/pipsqlipkgv1"
			},
			"versions": [
				"1.1.0",
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pipsqlipkgv1/MAL-2024-5541.json"
			}
		}
	],
	"references": [
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-PIPSQLIPKGV1-5932205"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04323",
				"import_time": "2024-06-28T02:49:46.804383243Z",
				"modified_time": "2024-06-25T13:38:39Z",
				"sha256": "1d0e2e3c67395634f53426376371868613e918d7c35afa554bdd3beaeff1bee6",
				"source": "reversing-labs",
				"versions": [
					"1.1.0",
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-08751",
				"import_time": "2024-10-24T00:59:39.399702871Z",
				"modified_time": "2024-10-16T14:46:06Z",
				"sha256": "95ac6f9b3434b3dcb66b2b6c8cb6c6273a2e2371518d9847b1dbad45ebea2b9e",
				"source": "reversing-labs"
			}
		]
	}
}
